import type { PresentationResult, PresentationTheme } from '@/types';

const themeColors: Record<PresentationTheme, { primary: string; secondary: string; accent: string; bg: string }> = {
  corporate: { primary: '0F4C81', secondary: '2E75B6', accent: 'E8A33D', bg: 'F0F4F8' },
  creative: { primary: '7B2D8E', secondary: 'C2410C', accent: 'DB2777', bg: 'FDF4FF' },
  minimal: { primary: '1E293B', secondary: '475569', accent: '0EA5E9', bg: 'F8FAFC' },
  bold: { primary: 'B91C1C', secondary: '1E3A5F', accent: 'F59E0B', bg: 'FEF2F2' },
};

export async function downloadPresentation(
  result: PresentationResult,
  theme: PresentationTheme
): Promise<void> {
  const pptxgen = (await import('pptxgenjs')).default;
  const pptx = new pptxgen();
  const colors = themeColors[theme];
  type BulletRow = { text: string; options: Record<string, unknown> };

  pptx.defineLayout({ name: 'LAYOUT_WIDE', width: 13.33, height: 7.5 });
  pptx.layout = 'LAYOUT_WIDE';

  // Title slide
  const titleSlide = pptx.addSlide();
  titleSlide.background = { color: colors.bg };
  titleSlide.addShape('rect', {
    x: 0, y: 0, w: 0.4, h: '100%',
    fill: { color: colors.primary },
  });
  titleSlide.addText(result.title, {
    x: 1.2, y: 2.2, w: 10, h: 1.5,
    fontSize: 36, bold: true, color: colors.primary,
    fontFace: 'Arial',
  });
  titleSlide.addText(result.subtitle, {
    x: 1.2, y: 3.8, w: 10, h: 1,
    fontSize: 18, color: colors.secondary,
    fontFace: 'Arial',
  });
  titleSlide.addText('Generated by FlowDesk AI', {
    x: 1.2, y: 5.8, w: 6, h: 0.5,
    fontSize: 11, color: '94A3B8', italic: true,
    fontFace: 'Arial',
  });

  // Content slides
  result.slides.slice(1).forEach((slide) => {
  const s = pptx.addSlide();
    s.background = { color: 'FFFFFF' };

    // Header bar
    s.addShape('rect', {
      x: 0, y: 0, w: '100%', h: 1.1,
      fill: { color: colors.primary },
    });
    s.addShape('rect', {
      x: 0, y: 1.1, w: '100%', h: 0.06,
      fill: { color: colors.accent },
    });

    s.addText(slide.title, {
      x: 0.6, y: 0.15, w: 12, h: 0.8,
      fontSize: 26, bold: true, color: 'FFFFFF',
      fontFace: 'Arial', valign: 'middle',
    });

    // Bullet points
    const bulletRows: BulletRow[] = slide.bulletPoints.map((bp, i) => ({
      text: bp,
      options: {
        fontSize: 18,
        color: '334155',
        fontFace: 'Arial',
        bullet: { type: 'bullet', characterCode: '2022', indent: 20 },
        breakLine: true,
        paraSpaceAfter: i === slide.bulletPoints.length - 1 ? 0 : 12,
      },
    }));

    s.addText(bulletRows, {
      x: 0.8, y: 1.6, w: 11.5, h: 4.5,
      valign: 'top',
    });

    // Speaker notes
    s.addNotes(slide.speakerNotes);

    // Footer
    s.addText('FlowDesk AI', {
      x: 11.5, y: 6.9, w: 2, h: 0.4,
      fontSize: 9, color: '94A3B8',
      fontFace: 'Arial', align: 'right',
    });
  });

  // Closing slide
  const closeSlide = pptx.addSlide();
  closeSlide.background = { color: colors.primary };
  closeSlide.addText('Thank You', {
    x: 0, y: 2.5, w: '100%', h: 1.2,
    fontSize: 40, bold: true, color: 'FFFFFF',
    fontFace: 'Arial', align: 'center',
  });
  closeSlide.addText('Questions & Discussion', {
    x: 0, y: 3.8, w: '100%', h: 0.8,
    fontSize: 20, color: colors.accent,
    fontFace: 'Arial', align: 'center',
  });
  closeSlide.addText('AI-generated content may require human review.', {
    x: 0, y: 5.5, w: '100%', h: 0.5,
    fontSize: 11, color: 'CBD5E1', italic: true,
    fontFace: 'Arial', align: 'center',
  });

  await pptx.writeFile({ fileName: `${result.title.replace(/[^a-zA-Z0-9]/g, '_')}_Presentation.pptx` });
}
